// m1/tokens-env.ts — publish this stack's six token ids as a SHELL-SOURCEABLE projection.
//
//   docker compose run --rm --no-deps issuer-tokens-env      (normally: run by entrypoint-deploy.sh)
//
// ── WHY THIS FILE EXISTS (00020 PR C) ───────────────────────────────────────
// Kernel #69 removed the local faucet contract, so the token ids the solver, the maker, the
// offer poster, the e2e driver and the shielded-night book chain all need are no longer
// derivable from a contract address: they are whatever THIS chain's issuer deployment produced.
// Every one of those consumers runs the KERNEL image, which has no reader for
// `metadata.undeployed.json` and must never grow one — `m1/registry.ts` in THIS image is the
// single reader, and it is the one that validates the file against the pinned tree's JSON
// schema and against the semantic validator the faucet site itself runs.
//
// So this script re-uses that same loader and writes a deliberately dull projection of it:
//
//   ISSUER_TOKENS_REVISION=<64 hex>
//   ISSUER_TOKENS_GENERATED_AT=<iso 8601>
//   ISSUER_TOKENS_NAMES="TWBTC TWETH TWUSDC TWUSDM UTWUSDC UTWBTC"
//   ISSUER_TOKEN_ID_TWBTC=<64 hex>          ISSUER_TOKEN_DECIMALS_TWBTC=8
//   ISSUER_TOKEN_PRIVACY_TWBTC=shielded     ISSUER_TOKEN_SYMBOL_TWBTC=twBTC
//   ISSUER_TOKEN_ADDRESS_TWBTC=<64 hex>     ISSUER_TOKEN_FAUCET_BASE_UNITS_TWBTC=100000000
//   …one block per token, in the pinned tree's canonical order
//
// `images/offerfiles-kernel/registry-env.sh` sources it (after checking every line matches a
// `NAME=value` grammar, because a sourced file runs). Nothing else reads it.
//
// ── WHY IT IS A SEPARATE VOLUME FROM THE REGISTRY ───────────────────────────
// `issuer-registry` is served over HTTP by the faucet's nginx. A file dropped beside
// `metadata.undeployed.json` would be inside a document root, and while nginx only aliases
// named paths today, "the token handoff happens to live in a web root" is a property nobody
// should have to re-check. `issuer-tokens` is mounted read-only by every consumer and is not
// served at all.
//
// ── ATOMIC, LIKE THE REGISTRY ITSELF ────────────────────────────────────────
// Written to `tokens.env.tmp-<pid>` in the SAME directory and renamed, so a consumer either
// sees the previous complete file or the new complete file and never a half-written one. That
// is also why every consumer mounts the DIRECTORY: a rename replaces the inode.
//
// EXIT CODES: 0 published; 1 the registry is unreadable/invalid, or a value failed its shape
// check. The values are re-validated HERE as well as in the shell, because this is the side
// that can say which token and which field.

import { rename, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { loadReadyRegistry, log, resolvedTokens } from "./lib.js";

const ROLE = "issuer-tokens-env";
const say = (message: string): void => log(ROLE, message);

const outDir = (process.env.ISSUER_TOKENS_DIR ?? "/srv/issuer-tokens").trim() || "/srv/issuer-tokens";
const outPath = resolve(outDir, "tokens.env");

/** The grammar `registry-env.sh` will accept. Enforced on this side too so a bad value is
 *  reported with the token and the field that produced it, rather than as one rejected line. */
const HEX64 = /^[0-9a-f]{64}$/;
const SYMBOL = /^[A-Za-z0-9]{1,32}$/;
const NAME = /^[A-Z][A-Z0-9]{0,31}$/;
const DIGITS = /^[0-9]+$/;
const ISO = /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9:.]+Z?$/;

function check(condition: boolean, message: string): void {
  if (!condition) {
    say(`FATAL: ${message}`);
    process.exit(1);
  }
}

const { registry, path: registryFile } = await loadReadyRegistry().catch((error) => {
  say(`FATAL: ${error instanceof Error ? error.message : String(error)}`);
  return process.exit(1) as never;
});

let tokens: ReturnType<typeof resolvedTokens>;
try {
  tokens = resolvedTokens(registry);
} catch (error) {
  say(`FATAL: ${error instanceof Error ? error.message : String(error)}`);
  process.exit(1);
}

check(HEX64.test(registry.registryRevision), `registryRevision ${registry.registryRevision} is not 64 hex`);
check(ISO.test(registry.generatedAt), `generatedAt ${registry.generatedAt} is not an ISO timestamp`);
check(tokens.length > 0, "the registry selects no active deployment at all");

const lines: string[] = [
  "# GENERATED by images/issuer/m1/tokens-env.ts — do not edit.",
  "#",
  "# The six token ids this chain's issuer deployment produced, as a shell-sourceable",
  "# projection of metadata.undeployed.json. Read by images/offerfiles-kernel/registry-env.sh;",
  "# the registry itself is parsed in exactly one place, images/issuer/m1/registry.ts.",
  `# source registry: ${registryFile}`,
  `ISSUER_TOKENS_REVISION=${registry.registryRevision}`,
  `ISSUER_TOKENS_GENERATED_AT=${registry.generatedAt}`,
  `ISSUER_TOKENS_NAMES="${tokens.map((token) => token.name).join(" ")}"`
];

for (const token of tokens) {
  check(NAME.test(token.name), `${token.symbol}: kernel name ${JSON.stringify(token.name)} is not [A-Z][A-Z0-9]*`);
  check(SYMBOL.test(token.symbol), `${token.symbol}: symbol is not alphanumeric`);
  check(HEX64.test(token.tokenId), `${token.name}: tokenId ${token.tokenId} is not 64 hex`);
  check(HEX64.test(token.contractAddress), `${token.name}: contractAddress is not 64 hex`);
  check(Number.isInteger(token.decimals) && token.decimals >= 0 && token.decimals <= 38,
    `${token.name}: decimals ${token.decimals} is outside the kernel schema's 0..38`);
  check(token.privacy === "shielded" || token.privacy === "unshielded", `${token.name}: privacy ${token.privacy}`);
  check(DIGITS.test(token.faucetBaseUnits), `${token.name}: faucetBaseUnits ${token.faucetBaseUnits} is not digits`);
  lines.push(
    "",
    `ISSUER_TOKEN_ID_${token.name}=${token.tokenId}`,
    `ISSUER_TOKEN_DECIMALS_${token.name}=${token.decimals}`,
    `ISSUER_TOKEN_PRIVACY_${token.name}=${token.privacy}`,
    `ISSUER_TOKEN_SYMBOL_${token.name}=${token.symbol}`,
    `ISSUER_TOKEN_ADDRESS_${token.name}=${token.contractAddress}`,
    `ISSUER_TOKEN_FAUCET_BASE_UNITS_${token.name}=${token.faucetBaseUnits}`
  );
}

const body = `${lines.join("\n")}\n`;
const tmp = `${outPath}.tmp-${process.pid}`;
await writeFile(tmp, body, { mode: 0o644 });
await rename(tmp, outPath);

process.stdout.write(
  `ISSUER_TOKENS_ENV path=${outPath} tokens=${tokens.length} revision=${registry.registryRevision} ` +
    `names=${tokens.map((token) => `${token.name}:${token.decimals}`).join(",")}\n`
);
say(`published ${tokens.length} token ids to ${outPath}`);
process.exit(0);
