#!/usr/bin/env bash
#
# Generate an env file with a random free host-port block above 10000, for running this
# stack on a shared machine (or a second instance beside an existing one).
#
#   ./scripts/pick-ports.sh > .env.test
#   ENV_FILE=.env.test ./up.sh
#
# Only the values that must not collide are emitted; everything else falls back to the
# defaults baked into the compose fragments and scripts/lib/common.sh. COMPOSE_PROJECT_NAME
# is randomized too, because two stacks sharing a project name share their volumes.
#
set -euo pipefail

BASE_MIN=${BASE_MIN:-10100}
BASE_MAX=${BASE_MAX:-64000}
BLOCK=${BLOCK:-16}   # how many consecutive ports the block must cover

port_free() {
  # A port is usable only if nothing is listening AND docker can bind it. `nc -z` probes the
  # former; that is enough in practice since docker's own bind failure surfaces loudly.
  if command -v nc >/dev/null 2>&1; then
    if nc -z 127.0.0.1 "$1" >/dev/null 2>&1; then return 1; fi
  else
    # bash's /dev/tcp needs no external binary.
    if (exec 3<>"/dev/tcp/127.0.0.1/$1") >/dev/null 2>&1; then return 1; fi
  fi
  return 0
}

block_free() {
  local base="$1" i
  for (( i = 0; i < BLOCK; i++ )); do
    port_free $(( base + i )) || return 1
  done
  return 0
}

BASE=""
for _ in $(seq 1 200); do
  cand=$(( BASE_MIN + (RANDOM % (BASE_MAX - BASE_MIN - BLOCK)) ))
  cand=$(( cand - cand % 10 ))   # keep the block readable
  if block_free "$cand"; then BASE="$cand"; break; fi
done
[[ -z "$BASE" ]] && { echo "could not find a free ${BLOCK}-port block in ${BASE_MIN}-${BASE_MAX}" >&2; exit 1; }

SUFFIX="${SUFFIX:-$BASE}"
# PROJECT_PREFIX lets a caller mark what generated the stack — scripts/ci-check.sh uses
# `midnight-1-offers-ci` so a leaked container is immediately attributable to a CI run rather
# than to somebody's laptop session.
PROJECT_PREFIX="${PROJECT_PREFIX:-midnight-1-offers}"
IMAGE_TAG_SUFFIX="${IMAGE_TAG_SUFFIX:-${PROJECT_PREFIX}-${SUFFIX}}"

cat <<EOF
# Generated by scripts/pick-ports.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# A disposable, collision-free stack: random project name + a free port block at ${BASE}.
COMPOSE_PROJECT_NAME=${PROJECT_PREFIX}-${SUFFIX}

# Every locally built image gets a run-specific tag. Unique ports and volumes alone are not
# enough on a shared daemon: fixed :local tags can race, or reuse a stale binary from another
# checkout of this repository.
POSTGRES_IMAGE=midnight-1-offers/postgres:${IMAGE_TAG_SUFFIX}
CELESTIA_IMAGE=midnight-1-offers/celestia:${IMAGE_TAG_SUFFIX}
KERNEL_IMAGE=midnight-1-offers/offerfiles-kernel:${IMAGE_TAG_SUFFIX}
FRONTEND_IMAGE=midnight-1-offers/zswap-da:${IMAGE_TAG_SUFFIX}
SOLVER_IMAGE=midnight-1-offers/cow-solver:${IMAGE_TAG_SUFFIX}
RELAY_IMAGE=midnight-1-offers/relay:${IMAGE_TAG_SUFFIX}
INTENTS_UI_IMAGE=midnight-1-offers/intents-ui:${IMAGE_TAG_SUFFIX}

# External runtime images: repository + IMMUTABLE DIGEST, never a tag. All three are good
# official multiarch indexes (linux/amd64 + linux/arm64). Readable versions: midnight-node
# 1.0.0, indexer-standalone 4.3.3, proof-server 8.1.0.
NODE_IMAGE=${NODE_IMAGE:-docker.io/midnightntwrk/midnight-node@sha256:ede01da35e982b6a4b85461ad8492ae2753ef14246fba33c8039b782aa8e39fb}
INDEXER_IMAGE=${INDEXER_IMAGE:-docker.io/midnightntwrk/indexer-standalone@sha256:03afd079b00bcd229df29a24771439c5e7695c339cd89216d0763ce40731cc4b}
PROOF_IMAGE=${PROOF_IMAGE:-docker.io/midnightntwrk/proof-server@sha256:801bbc0340e9e96f16735f77b523f23c7459e3359842f7c79c2c53f4e994d531}

# Warehouse-backed binaries (Celestia). Which release, never which bytes: the SHA-256 pins
# live in the image Dockerfiles and config/artifact-decisions.json.
WAREHOUSE_REPO=${WAREHOUSE_REPO:-effectstream/binaries}
WAREHOUSE_RELEASE=${WAREHOUSE_RELEASE:-0.3.120}

BIND_ADDR=127.0.0.1
NODE_HOST_PORT=$(( BASE + 0 ))
INDEXER_HOST_PORT=$(( BASE + 1 ))
PROOF_HOST_PORT=$(( BASE + 2 ))
KERNEL_HOST_PORT=$(( BASE + 3 ))
BATCHER_HOST_PORT=$(( BASE + 4 ))
CELESTIA_HOST_PORT=$(( BASE + 5 ))
FRONTEND_HOST_PORT=$(( BASE + 6 ))
RELAY_HTTP_HOST_PORT=$(( BASE + 7 ))
RELAY_WS_HOST_PORT=$(( BASE + 8 ))
INTENTS_UI_HOST_PORT=$(( BASE + 9 ))

# THE BROWSER RUNS OUTSIDE COMPOSE, so every endpoint the page touches has to be a HOST
# endpoint. The SPA's own fallbacks (http://<pageHost>:9999, :3334) and the kernel-config
# hostname rewrite both keep the DEFAULT/CONTAINER port, which a generated block by definition
# does not publish — so a random-port stack MUST inject all six or the browser fetches from
# ports nothing is listening on. The last four are folded into GET /v1/midnight/config by
# images/zswap-da/browser-network-urls.patch; FRONTEND_NODE_URI has no counterpart there at
# all (the kernel reports no node URI) and is what the in-page JS wallet dials.
FRONTEND_API_BASE=http://127.0.0.1:$(( BASE + 3 ))
FRONTEND_BATCHER_URL=http://127.0.0.1:$(( BASE + 4 ))
FRONTEND_NODE_URI=http://127.0.0.1:$(( BASE + 0 ))
FRONTEND_INDEXER_URI=http://127.0.0.1:$(( BASE + 1 ))${INDEXER_API_PATH:-/api/v3/graphql}
FRONTEND_INDEXER_WS_URI=ws://127.0.0.1:$(( BASE + 1 ))${INDEXER_API_PATH:-/api/v3/graphql}/ws
FRONTEND_PROOF_SERVER_URI=http://127.0.0.1:$(( BASE + 2 ))

INDEXER_SECRET=303132333435363738393031323334353637383930313233343536373839303132

NODE_WAIT_TIMEOUT=${NODE_WAIT_TIMEOUT:-180}
INDEXER_WAIT_TIMEOUT=${INDEXER_WAIT_TIMEOUT:-420}
PROOF_WAIT_TIMEOUT=${PROOF_WAIT_TIMEOUT:-120}
CELESTIA_WAIT_TIMEOUT=${CELESTIA_WAIT_TIMEOUT:-300}
KERNEL_WAIT_TIMEOUT=${KERNEL_WAIT_TIMEOUT:-600}
FRONTEND_WAIT_TIMEOUT=${FRONTEND_WAIT_TIMEOUT:-300}
RELAY_WAIT_TIMEOUT=${RELAY_WAIT_TIMEOUT:-300}
SOLVER_WAIT_TIMEOUT=${SOLVER_WAIT_TIMEOUT:-300}
EOF
